Update Mac Readme and add LFS + Hardware Virtualisation instructions
playmint/ds pull request #1006
Opened 2024-02-02 12:35 UTC by ldunnplaymint

resolves: #1058

2024-02-02 14:17 UTC, ldunnplaymint commented
I would like @5p0rt5BEArD to check this one, mostly to sanity check the steps for OSX setup

2024-02-05 10:54 UTC, chrisfarms approved these changes
LGTM

2024-02-05 16:43 UTC, 5p0rt5BEArD commented
I'm going to test this on the freshly restored Mac

2024-02-07 16:20 UTC, ldunnplaymint commented
I have cleaned up the readme a bit in this PR since Farm's approved it, will need another tick before it gets merged

2024-02-08 15:51 UTC, 5p0rt5BEArD requested changes
A few changes - I can make these :)

2024-02-08 15:51 UTC, 5p0rt5BEArD commented on README.md
> +- **Install Abigen:** Visit [Abigen](https://geth.ethereum.org/downloads)
```suggestion
- `brew tap ethereum/ethereum`
- `brew install ethereum`
```

2024-02-08 15:51 UTC, 5p0rt5BEArD commented on README.md
> +### 4. Install Abigen
```suggestion
### 4. Install Ethereum Tools
```

2024-02-08 15:51 UTC, 5p0rt5BEArD commented on README.md
> +### 5. Install NPM
should also add `nvm use` to be

2024-02-19 14:00 UTC, chrisfarms commented
![Screenshot 2024-02-19 at 13 59 06](https://github.com/playmint/ds/assets/45921/b4d91d77-c04b-45ba-95e5-19521ed2f160)

that capitalisation inconsistency puts me on edge 😄

2024-02-19 14:22 UTC, chrisfarms commented on README.md
> +<summary>Installation Instructions</summary>
I feel like having this expandable section which is already within an exandable second is quite hard to follow .... maybe we should consider breaking out all this "help with installing dependencies" bit into it's own `deps.md` file and just link to it

2024-02-19 14:22 UTC, chrisfarms commented on README.md
> +### Building from source (for production)
I don't think this section really makes sense any more ... the command is wrong, and there's no real need for anyone to do a "production" build.

If we did think it's worth keeping ... we should change it to just say something like:

```
A [github actions workflow](https://github.com/playmint/ds/actions) will build
production container images tagged with the commit sha on every merge to main
```

2024-02-19 15:45 UTC, 5p0rt5BEArD commented on README.md
> +### Building from source (for production)
seems like a Playmint org level instruction anyway - I'll kill the section

2024-02-19 15:46 UTC, 5p0rt5BEArD commented on README.md
> +<summary>Installation Instructions</summary>
I think a separate .md for the tool installation instructions would help yes

Is there a convention for readme.md across multiple files?

2024-02-19 16:03 UTC, 5p0rt5BEArD approved these changes
Approved after making my own edits

2024-02-19 16:36 UTC, chrisfarms commented on README.md
> +<summary>Installation Instructions</summary>
not that I'm aware of ... what you have done looks good to me 👍

2024-02-19 16:44 UTC, chrisfarms approved these changes
LGTM 

did notice there's another "fold within a fold" in the docker section for the troubleshooting ... that could probably be broken out to avoid that odd UX like before ... but seems super nitty, it looks good

2024-02-20 13:24 UTC, merged