Unit Team Distinction (Change color of a unit from plugin)
playmint/ds pull request #1044
Opened 2024-02-14 18:15 UTC by Steedie

## What
Changes to Unity and the frontend to allow a mobile unit's color to be changed from plugins.

### Unity diorama
![image](https://github.com/playmint/ds/assets/27741109/ee377fcf-f50e-4224-88c5-9f4a4e75e17e)

### Custom plugin changing unit's color
![image](https://github.com/playmint/ds/assets/27741109/2b5f081d-148d-42bd-93e7-e31bc58bacbb)

## [Why](https://github.com/orgs/playmint/projects/1/views/1?pane=issue&itemId=52368565)
This has been a common request during our playtests of Duck Burger, Hexcraft, and more.
_"As a team based experience maker I want to show which team each Unit is on so players can see whats going on"_

## How
First, changes in Unity to MobileUnitData, MobileUnitController, and MobileUnitDiorama, resulting in the diorama screenshot above.
Then changes to the frontend, mostly following the format of how plugins can change tile colours.

## Info
To test this in a local build, I created a very simple custom plugin and hard-coded my unit's ID into the map:
```js
    const mapObj = [];
    mapObj.push(
        {
            type: "unit",
            key: "color",
            id: "0x0945e868000000000000000000000000000000000000033b",
            value: "255,198,0",
        }
    )

    return {
        version: 1,
        map: mapObj, ....
```

The unit's material shader is different from the tile shader and therefore is using R,G,B instead of hex for colour input. The implemented code expects the colour value to look like "123,123,123", or just "0" sets it back to default.

Resolves #1023

2024-02-14 18:37 UTC, Steedie commented
Having trouble running csharpier on Windows CMD:
![image](https://github.com/playmint/ds/assets/27741109/86d855a9-e52e-4566-bc6c-950eebbafe57)
Can't remember how I did it last time

2024-02-15 07:02 UTC, chrisfarms commented
> Having trouble running csharpier on Windows CMD:

try:

```
cd map
dotnet tool run dotnet-csharpier .
```

2024-02-15 13:28 UTC, chrisfarms requested changes

2024-02-15 13:28 UTC, chrisfarms commented on frontend/src/components/map/MobileUnit.tsx
> +        randomUnitProperties: PluginMapProperty[];
hehe as much as it makes me laugh that the `randomProperties` from the initial test example has created a new standard, we should probably name this more sensibly to avoid confusion.

maybe `pluginProperties` or something like that.

2024-02-15 13:28 UTC, chrisfarms commented on map/Assets/Scripts/Components/MobileUnit/MobileUnitController.cs
> +            Color newColor = RGBStringToColor(_nextData.color);
does this need to be a special case of only accepting RGB values?

it might be less of a footgun if the `color` property on units, worked the same way that it works on other components where it accepts CSS color values.

Example of using the ColorUtility here: https://github.com/playmint/ds/blob/main/map/Assets/Scripts/Components/Tile/TileController.cs#L45

2024-02-15 17:43 UTC, Steedie commented on map/Assets/Scripts/Components/MobileUnit/MobileUnitController.cs
> +            Color newColor = RGBStringToColor(_nextData.color);
Ah just what I needed! This is now implemented:
```cs
            string colorString = _nextData.color;
            if (!string.IsNullOrEmpty(colorString) && !colorString.StartsWith("#"))
            {
                colorString = "#" + colorString;
            }
            else if (string.IsNullOrEmpty(colorString))
            {
                colorString = "#" + _defaultBodyColor;
            }

            ColorUtility.TryParseHtmlString(colorString, out Color targetColor);
            renderers[0].material.color = targetColor;
```

2024-02-16 09:09 UTC, chrisfarms commented on map/Assets/Scripts/Components/MobileUnit/MobileUnitController.cs
> +            if (!string.IsNullOrEmpty(colorString) && !colorString.StartsWith("#"))
non-blocking: I _believe_ TryParseHtmlString handles more than just `#` prefixed color strings ... for example `red` and `rgb(0,0,0)` are both valid ... so it looks like this bit where it forces the `#` prefix might break those things, if I'm reading it right. .... non-blocking since I think in reality we do use the hex values, so it's probably a non-issue

2024-02-16 09:09 UTC, chrisfarms approved these changes

2024-02-16 10:57 UTC, Steedie commented on map/Assets/Scripts/Components/MobileUnit/MobileUnitController.cs
> +            if (!string.IsNullOrEmpty(colorString) && !colorString.StartsWith("#"))
Good point. I've now modified this so it works according to Unity's [ColorUtility.TryParseHtmlString documentation](ColorUtility](https://docs.unity3d.com/ScriptReference/ColorUtility.html).TryParseHtmlString)

These are examples of inputs that now work: "#f00", "#ff0000", "f000", "ff000000", and "red".
"ff0000" no longer works, but allows inputs like "red", and "orange" to also work.

2024-02-16 13:21 UTC, merged