Make the readme a bit clearer
playmint/ds pull request #1243
Opened 2024-04-04 11:49 UTC by ldunnplaymint

We want to make it so the tutorial readme flows a bit better, it isn't currently explicit what to do on the page.

2024-04-04 12:20 UTC, Steedie requested changes

2024-04-04 12:20 UTC, Steedie commented on tutorial/README.md
> +- The Existing Maps are various things that Playmind has created in Downstream. There are some smaller examples like the Gate Demo and some larger examples like the quest-map.
```suggestion
The Existing Maps are various things that Playmint has created in Downstream. There are some smaller examples like the Gate Demo and some larger examples like the quest-map.
```
Playmind -> Playmint

2024-04-04 12:22 UTC, Steedie approved these changes

2024-04-04 13:53 UTC, chrisfarms reviewed
personally I would skip over a block of text like this, so there's maybe an argument for making it a little more call-to-actiony rather than introy ... but I think I might be the minority here so probably ignore me.

I've noticed that the references link at the bottom of the page is broken, so prob worth fixing up in this PR ... or does the note in the intro replace the section in the footer?

2024-04-04 13:53 UTC, chrisfarms commented on tutorial/README.md
> +- Once you feel you are up to speed on what is currently possible on Downstream, you can check out our Existing Maps and Games!
a list with only one thing probably doesn't deserve to be a list :)

```suggestion
Once you feel you are up to speed on what is currently possible on Downstream, you can check out our Existing Maps and Games!
```

2024-04-04 13:53 UTC, chrisfarms commented on tutorial/README.md
> +The Existing Games are full games that have been developed by external developers and one by Playmint! They will give you an insight into how far Downstream has already been pushed!
look like you intended this to be a linebreak, but didn't give it the extra space? 

```suggestion

The Existing Games are full games that have been developed by external developers and one by Playmint! They will give you an insight into how far Downstream has already been pushed!
```

2024-04-04 13:53 UTC, chrisfarms commented on tutorial/README.md
> +For more in depth information, check out the References page!
Not sure it's really "more in depth" just different

and should it be a link?

```suggestion
See the [References](./REFERENCE.md) for information on common tooling and commands.
```

or something like that

2024-04-04 14:22 UTC, chrisfarms approved these changes

2024-04-04 16:13 UTC, merged

2024-04-05 11:23 UTC, chasensa commented
@ldunnplaymint is it worth adding the Discord support chat link at the end of the intro? 

something like: (feel free to change!) 
Specific questions? Drop into our Discord support chat where you can have direct access to the Playmint dev team: https://discord.gg/MvYb9PBjGW